qdrant/qdrant-client

poetry.lock, pyproject.toml, qdrant_openapi_client/models/models.py, tests/test_qdrant_client.py
fix for  - https://github.com/qdrant/qdrant_client/issues/14
=> Fix payload type parsing

tools/DEVELOPMENT.md, tools/generate_rest_client.sh
- Script for updating REST client
- ReadMe instruction & checklist
=> clients update instruction

qdrant_client/conversions/conversion.py, tests/test_qdrant_client.py
Adds explicit test for using match value condition
=> add test for match condition

README.md, docs/source/index.rst
README lacked the example of pushing some vectors into the collection.
=> Add an example of inserting points into the README

qdrant_client/qdrant_client.py, qdrant_client/uploader/grpc_uploader.py, qdrant_client/uploader/rest_uploader.py, qdrant_client/uploader/uploader.py
=> Enable named vectors uploading in `.upload_collection()` and retry logic

poetry.lock, pyproject.toml, qdrant_client/connection.py, qdrant_client/qdrant_client.py, qdrant_client/qdrant_remote.py, tests/test_async_qdrant_client.py
Expose raw async gRPC client. Channel is created by default Qdrant client, but raw queries function could be used to speed optimization
=> expose raw async grpc client

.github/workflows/integration-tests.yml, tests/benches/test_grpc_upload.py, tests/benches/test_rest_upload.py, tests/congruence_tests/test_common.py, tests/integration-tests.sh, tests/test_in_memory.py, tests/type_stub.py
We were not launching the tests on platforms different than Ubuntu. This PR enables testing on MacOS.
There are still some issues with Docker on Windows, so it wasn't enabled.
=> [WIP] Enable testing on macos

tests/test_in_memory.py, tests/test_local_persistence.py
Small improvements for the in-memory and local persistence tests 
This is my first contribution to Qdrant :)
=> test: Improve inmemory and local persistence tests

.github/workflows/integration-tests-macos.yml, .github/workflows/integration-tests.yml, tests/integration-tests.sh
As discussed @generall, suggesting removal from macOS. Please review and — merge if you agree with the recommendation.
=> Remove MacOS from PR CI

README.md
=> Fix API Param in README

qdrant_client/local/payload_filters.py, qdrant_client/local/tests/test_payload_filters.py
picking up Luis's comments left in #272
=> code refactor and better naming

qdrant_client/http/__init__.py, qdrant_client/http/api_client.py, qdrant_client/http/models/models.py, qdrant_client/local/local_collection.py, tests/test_qdrant_client.py
- Fix related to https://github.com/qdrant/qdrant-client/issues/320
- Update payload selector in local mode
=> update payload selector and tests

qdrant_client/qdrant_client.py
In the upload_records function the wait argument was not passing to the client. 
=> Adding forgotton wait to the upload records

docs/source/examples/install.rst, docs/source/index.rst
* docs(index.rst): remove unnecessary lines from indices and tables section
=> Add Right Pane Table of Contents

docs/source/conf.py, docs/source/examples/install.rst, docs/source/examples/quickstart.ipynb, docs/source/index.rst, poetry.lock, pyproject.toml, tools/generate_docs.sh, tools/generate_docs_netlify.sh
1. Add Notebook support in the docs build itself
2. Adds a new section: Examples, with a Quickstart notebook!
=> Add Executable Quickstart Example

.gitignore, qdrant_client/local/distances.py, tests/congruence_tests/test_recommendation.py, tests/integration-tests.sh
All the context is in qdrant/qdrant#2904
This PR updates local client to reflect those changes
=> Update recommend `best_score`  formula

qdrant_client/async_qdrant_client.py, qdrant_client/local/async_qdrant_local.py, qdrant_client/local/local_collection.py, qdrant_client/local/persistence.py, qdrant_client/local/qdrant_local.py, qdrant_client/qdrant_client.py
Allow users to be responsible for data integrity in local mode
=> force_disable_check_same_thread flag

qdrant_client/async_qdrant_client.py, qdrant_client/async_qdrant_remote.py, qdrant_client/connection.py, qdrant_client/qdrant_client.py, qdrant_client/qdrant_remote.py, tests/test_qdrant_client.py
=> new: expose grpc options in client

qdrant_client/local/local_collection.py, tests/congruence_tests/test_updates.py
=> fix: forbid nan in payload in local mode to restore congruence

qdrant_client/http/api/cluster_api.py, qdrant_client/http/api/collections_api.py, qdrant_client/http/api/points_api.py, qdrant_client/http/api/service_api.py, qdrant_client/http/api/snapshots_api.py
https://github.com/qdrant/pydantic_openapi_v3/pull/21
https://github.com/qdrant/qdrant-client/issues/310
=> fix: replace data with content to fix httpx deprecation warning

pyproject.toml
=> Update the urlllib3 package dependency to make it compatible with v2

qdrant_client/local/async_qdrant_local.py, qdrant_client/local/qdrant_local.py, qdrant_client/uploader/uploader.py, tests/congruence_tests/test_sparse_updates.py, tests/congruence_tests/test_updates.py, tests/test_qdrant_client.py
=> Replace auto int id with UUID

docs/source/index.rst
I was following the guide and my code wasn't working when reusing the quick start code snippet. Here is the snippet but with the relevant imports added.
=> Adds missing import in documentation example

qdrant_client/async_qdrant_client.py, qdrant_client/qdrant_client.py
It was initially fixed by @tjbai and @coszio , and then I came and broke their PR :( #458
=> Fix grpc typo

README.md
=> docs: add batching recommendation to readme

qdrant_client/conversions/conversion.py, qdrant_client/local/payload_filters.py, tests/fixtures/filters.py, tests/fixtures/payload.py
- local mode for datetime ranges
- add datetime ranges to random filter fixture
- discover a grpc validation bug in core 😮 -> https://github.com/qdrant/qdrant/pull/3742
=> Add support for datetime ranges

qdrant_client/local/payload_value_setter.py
An attempt to refactor spaghetti-code
=> refactor: refactor local mode payload setter

qdrant_client/conversions/conversion.py, tests/conversions/test_validate_conversions.py
=> fix: fix sparse vector conversion

qdrant_client/async_qdrant_remote.py, qdrant_client/qdrant_remote.py, tests/test_qdrant_client.py
Solves https://github.com/qdrant/qdrant-client/issues/590
=> fix: Fix read consistency when performing batch search

docs/source/quickstart.ipynb
=> docs: small typo fix of extra word in quickstart

qdrant_client/async_qdrant_remote.py, qdrant_client/qdrant_remote.py, tests/congruence_tests/test_recommendation.py
Allows setting the recommend strategy as a string when using grpc.
Reported in Discord: https://discord.com/channels/907569970500743200/1247469389494616106
=> allow string `RecommendStrategy` with `prefer_grpc=True`

qdrant_client/conversions/conversion.py, tests/conversions/fixtures.py, tests/conversions/test_validate_conversions.py
=> new: add conversions pt.1

qdrant_client/local/local_collection.py, tests/congruence_tests/test_discovery.py, tests/congruence_tests/test_recommendation.py
Fix based on https://github.com/qdrant/qdrant/pull/4551 and https://github.com/qdrant/qdrant/pull/4553
=> fix: do not exclude ids from lookup collection from search

qdrant_client/async_client_base.py, qdrant_client/async_qdrant_client.py, qdrant_client/async_qdrant_fastembed.py, qdrant_client/async_qdrant_remote.py, qdrant_client/client_base.py, qdrant_client/conversions/conversion.py, qdrant_client/local/async_qdrant_local.py, qdrant_client/local/local_collection.py, qdrant_client/local/qdrant_local.py, qdrant_client/qdrant_client.py, qdrant_client/qdrant_fastembed.py, qdrant_client/qdrant_remote.py, tests/congruence_tests/test_discovery.py, tests/congruence_tests/test_recommendation.py, tests/conversions/fixtures.py, tests/conversions/test_validate_conversions.py, tests/test_fastembed.py, tools/async_client_generator/transformers/fastembed/function_def_transformer.py
Because of backward compatibility
=> rollback fast-embed query method

tests/congruence_tests/test_query.py
ruff went crazy
the actual fix is increasing the limit for context query
```
-            limit=10,
+            limit=1000,
```
=> fix: increase context search limit

qdrant_client/local/async_qdrant_local.py, qdrant_client/local/qdrant_local.py, tests/congruence_tests/test_query.py
Add a congruence test that compare results for the request with `lookup_from` (collection + vector)
=> Add lookup_from test

qdrant_client/conversions/common_types.py, qdrant_client/local/async_qdrant_local.py, qdrant_client/local/local_collection.py, qdrant_client/local/multi_distances.py, qdrant_client/local/order_by.py, qdrant_client/local/qdrant_local.py, qdrant_client/local/tests/test_distances.py, qdrant_client/local/tests/test_referenced_vectors.py, qdrant_client/qdrant_fastembed.py, tests/congruence_tests/test_common.py, tests/congruence_tests/test_multivector_updates.py, tests/congruence_tests/test_query.py, tests/congruence_tests/test_query_batch.py, tests/congruence_tests/test_updates.py, tests/fixtures/points.py
Implementation of local mode for `query`.
~~No tests added yet~~
=> universal-query: Local mode

README.md
* [ x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [ x] Have you followed the guidelines in our Contributing document?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
=> [README.md] "here"-links are evil

tests/fixtures/points.py, tests/test_migrate.py
=> Test migration of multivectors and sparse vectors

qdrant_client/migrate/migrate.py
=> Refactor retry during migration

qdrant_client/local/async_qdrant_local.py, qdrant_client/local/local_collection.py, qdrant_client/local/qdrant_local.py, tests/congruence_tests/test_query.py
=> fix: do not modify input structs in-place

tests/congruence_tests/test_nested_filter.py, tests/congruence_tests/test_query.py
it's a fix for a branch I spoiled https://github.com/qdrant/qdrant-client/pull/704
=> Grpc comparison in tests

qdrant_client/async_qdrant_client.py, qdrant_client/async_qdrant_fastembed.py, qdrant_client/http/models/models.py, qdrant_client/qdrant_client.py, qdrant_client/qdrant_fastembed.py, tests/test_fastembed.py, tests/test_qdrant_client.py, tools/full_structures.json, tools/generate_rest_client.sh, tools/structures.json
=> new: remove default hybrid search for query_points with fastembed

tools/async_client_generator/transformers/function_def_transformer.py
=> fix: handle type_params for Python 3.12+

tests/congruence_tests/test_query.py, tests/test_async_qdrant_client.py, tests/test_fastembed.py, tests/test_migrate.py, tests/test_qdrant_client.py, tests/utils.py
=> improved semver comparison

qdrant_client/local/local_collection.py, tests/congruence_tests/test_common.py
=> fix: fix update_vectors in local mode, fix record comparison in tests

qdrant_client/async_client_base.py, qdrant_client/async_qdrant_client.py, qdrant_client/async_qdrant_remote.py, qdrant_client/client_base.py, qdrant_client/conversions/common_types.py, qdrant_client/conversions/conversion.py, qdrant_client/local/async_qdrant_local.py, qdrant_client/local/local_collection.py, qdrant_client/local/qdrant_local.py, qdrant_client/qdrant_client.py, qdrant_client/qdrant_remote.py, tests/congruence_tests/test_common.py, tests/congruence_tests/test_search_distance_matrix.py, tests/conversions/fixtures.py
This PR adds the support for the new distance matrix API.
It contains the remote and local implementation.
More details about the distance matrix API are available in the [design document](https://www.notion.so/qdrant/Distance-Matrix-API-f5ba55b9025d4fc49b532ee7b40cd0ae) and in the [PRs](https://github.com/qdrant/qdrant/milestone/11?closed=1) for the server implementation.
=> Feature: Distance Matrix API

qdrant_client/async_qdrant_fastembed.py, qdrant_client/qdrant_fastembed.py
=> fix: add local files only to set sparse model

qdrant_client/local/async_qdrant_local.py, qdrant_client/local/qdrant_local.py, tests/congruence_tests/test_query.py
prefetch input was not correctly resolved in local mode when prefetch was provided not in a list
=> fix: fix resolve prefetch input

qdrant_client/parallel_processor.py
When parallel is not none, and you are uploading points to Qdrant remote, and it is not responding or paused, then it will wait till processing_timeout (6 min) finishes then it will raise and the program will hangs.
The problem is the queue threads are not joined, and to join them we have to clean them properly if something happens.
=> fix: Clean up resources when qdrant not responding while uploading to elevate deadlock

qdrant_client/embed/schema_parser.py
fix a recently introduced mistake with path type hint
=> fix: fix type hint

qdrant_client/async_qdrant_fastembed.py, qdrant_client/fastembed_common.py, qdrant_client/qdrant_fastembed.py, tests/test_fastembed.py, tools/async_client_generator/fastembed_generator.py
=> function to get embeddings size

qdrant_client/embed/common.py, qdrant_client/embed/embedder.py, qdrant_client/fastembed_common.py, tests/embed_tests/test_local_inference.py
=> tests: Updated propagate options test

.github/workflows/integration-tests.yml, tests/test_qdrant_client.py
=> [WIP] Fix backward compatibility strict mode

tools/generate_grpc_client.sh, tools/generate_rest_client.sh
small cleanup suggestions, use python3.10 instead of just python
=> nit: some generators improvements

.github/workflows/type-checkers.yml, qdrant_client/local/local_collection.py, qdrant_client/local/multi_distances.py, qdrant_client/local/payload_filters.py, qdrant_client/local/sparse_distances.py
=> Unlock numpy ci

tests/embed_tests/test_local_inference.py
this refactoring reduces the time required to run these tests on local machine from 3.5 minutes to ~40 seconds
After reviewing the tests, I figured out, that congruence tests are not required here, cuz here we're testing the code which is the same for both local and remote modes, also it does not make sense running it with both http and grpc for the same reason.
Also @hh-space-invader tried caching embedding generation itself, however, after a couple of benchmarks, I've got the results which show that caching embedding generation won't bring as much benefits
=> refactor: refactor test local inference

qdrant_client/local/local_collection.py, tests/congruence_tests/test_query.py
do not propagate offsets into prefetches, fix offset usage in random sampling
=> Rethink offset prefetch

qdrant_client/local/local_collection.py, tests/congruence_tests/test_scroll_order_by.py
In congruence with qdrant/qdrant#6233, we deduplicate same value and id points
=> dedup `order_by` by value and id

tests/test_remote_inference.py
replace `get_embedding_size` with hard-coded value, cause when using cloud inference fastembed is not required to be installed
add query_points call
=> tests: extend remote inference tests
