- .github/workflows/integration-tests.yml
- poetry.lock
- pyproject.toml
Typing-extensions package has been updated to ^4.0.0 to make qdrant-client compatible with pytorch-lightning. The change doesn't seem to break anything. In addition to that, the integration tests are set up to use python 3.7, 3.8, 3.9 and 3.10.
> Upgrade typing-extensions to ^4.0.0

- .gitignore
- poetry.lock
- pyproject.toml
- qdrant_client/__init__.py
- qdrant_client/qdrant_client.py
- qdrant_client/uploader/grpc_uploader.py
- qdrant_client/uploader/rest_uploader.py
The batchers (REST & gRPC) are creating each a dedicated client for communicating with the server.
Those clients are not aware of the latest changes in https://github.com/qdrant/qdrant_client/pull/61 regarding the api-key, https & http2.
The batchers API need to evolve to accept additional arguments in order to have fully formed clients underneath.
So far this PR proposes to propagate the `kwargs` along the way for the `RestBatchUploader` but it gets a bit messy.
A similar approach is also necessary to create the channel of the `GrpcBatchUploader`.
> [WIP] propagate client kwargs to batchers

- qdrant_client/conversions/conversion.py
The `grpc.PayloadSchemaType.Text` was not correctly converted to the corresponding REST type. That was leading to an exception:
```ValueError: invalid PayloadSchemaType model: 5```
> Fix text schema type conversion (gRPC->REST)

- qdrant_client/qdrant_client.py
Hi 👋  I didn't find a contributing documentation but I took the freedom to create this PR so maybe you will agree to add this feature to the python client.
We would like to send requests to our Qdrant cluster on the same domain name as our API but with a prefix `/qdrant` for example (e.g. `api.inarix.com/qdrant`).
I added an optional `prefix` argument to the constructor and merged it to the rest uri if it exists.
Feel free to tell me what I need to do to be accepted and merged 😄
> Add `prefix` optional argument

- qdrant_client/qdrant_client.py
I've added the missing return statement to the `QdrantClient.delete` method for when HTTP is used.
> Fix `delete` missing return when HTTP

- qdrant_client/qdrant_client.py
- tests/test_qdrant_client.py
Related issue: https://github.com/qdrant/qdrant_client/issues/84
Added explicit `timeout` parameter to `QdrantClient`.
Parameter affects both REST and gRPC requests.
> explicit timeout param

- .github/workflows/integration-tests.yml
- poetry.lock
- pyproject.toml
- qdrant_client/conversions/common_types.py
The current limit on the Python version in `pyproject.toml` (`python = ">=3.7,<=3.11"`) rules out point release versions of Python 3.11 (e.g. the current version 3.11.2) while allowing 3.11.0. The limit has been introduced in https://github.com/qdrant/qdrant_client/pull/95 (previously `python = ">=3.7,<4.0"`). This PR changes it to `<3.12`.
> Increase Python version limit to <3.12

- qdrant_client/conversions/conversion.py
This speeds up serialization from one second to 22ms in some cases
> skip validation while converting scored points

- qdrant_client/local/local_collection.py
- tests/congruence_tests/test_updates.py
While upserting a batch of points, I found out the ids are converted to ints, even though I provided UUID-like identifiers. This PR fixes that. It seems the wrong variable was used.
> Use point id in batch upsert

- qdrant_client/local/payload_filters.py
I fixed the case when a particular payload does not have a corresponding attribute. In such a case, we have `value = None`, and the condition ends with `TypeError: argument of type 'NoneType' is not iterable`
> Fix MatchText filters in local mode

- qdrant_client/connection.py
Fixes <https://github.com/qdrant/qdrant-client/issues/171>.
This changes the gRPC message size limit to be unlimited.
I'm not sure huge messages are a good idea. We may want to do chunk streaming instead where possible. But this at least matches the Qdrant server configuration. Let me know if we prefer to change it to something different instead, such as 1GB or configurable.
> Make gRPC client message size unlimited

- tools/DEVELOPMENT.md
I was struggling to run the `generate_rest_client.sh` script successfully, until 
getting help from @agourlay. Turns out there are differences between `sed` in linux 
and in mac. 
The solution is quite simple: mac users will just have to install 
`gnu-sed` with `brew install gnu-sed` and alias it to regular `sed` using the install instructions
> Add gnu-sed instructions for macOS in DEVELOPMENT.md

- qdrant_client/connection.py
This fixes issue #179 by removing the incorrect `metadata` argument to the `grpc.insecure_channel()` call
> Fix incorrect args for grpc.insecure_channel()

- qdrant_client/http/models/models.py
https://github.com/qdrant/pydantic_openapi_v3/pull/9
> new: forbid extra fields in pydantic models

- qdrant_client/local/local_collection.py
- qdrant_client/qdrant_client.py
- tests/congruence_tests/test_common.py
This PR enables the normalization of vectors if cosine distance is used as reported in #212. It also enables vector comparison in tests, as the previous scroll call did not return vectors. In addition to that, the vectors are compared with `atol=1e-3` as random vectors are rounded upon generation: https://github.com/qdrant/qdrant-client/blob/bc08733e77fa3c2860177c90247ddcc8492a34a9/tests/fixtures/points.py#L15
> Fix cosine normalization

- docs/source/index.rst
The `top` keyword argument [is now](https://github.com/qdrant/qdrant-client/blob/ba8063ba897007886393ca403885be1faf8b21c5/qdrant_client/client_base.py#L27) `limit` in v1.3.x. The docs didn't reflect that, so this has been fixed.
> Change `top` kwarg to `limit` as per code

- qdrant_client/qdrant_remote.py
I was able to reproduce the problem, reported by our users some time ago, regarding random 
```
qdrant_client.http.exceptions.ResponseHandlingException: Server disconnected
```
errors in in consequent calls in FastAPI.
Here is a some fragment to reproduce:
```
app = FastAPI()
client = QdrantClient(
url=os.getenv("QDRANT_URL", "http://localhost:6333"),
api_key=os.getenv("QDRANT_API_KEY"),
)
@app.get("/api")
def read_root():
client.get_collections()
client.get_collections()
return client.get_collections()
```
Query with:
```
seq 1000 | xargs -P 2 -I {} curl 'localhost:8000/api'
```
( full code to reproduce available at request)
the error is reproducible with raw httpx Client as well, so it is not some problem of the client wrapper.
Turns out the core reason is usage of http2 in out cloud …
> disable forcing of http2 for cloud connections

- qdrant_client/client_base.py
- qdrant_client/conversions/common_types.py
- qdrant_client/local/local_collection.py
- qdrant_client/local/qdrant_local.py
- qdrant_client/qdrant_client.py
- qdrant_client/qdrant_remote.py
- tests/congruence_tests/test_common.py
- tests/congruence_tests/test_delete_points.py
- tests/congruence_tests/test_optional_vectors.py
- tests/test_qdrant_client.py
Fixes <https://github.com/qdrant/qdrant-client/issues/270>.
- Add tests for vector updates and deletes
- Fix problems with those methods
- Fix type matching
- Fix test error in case of deleted vectors (related to the new logic of vector deletion, changed in https://github.com/qdrant/qdrant/pull/2514 )
> add tests for vector operations

- .github/workflows/integration-tests.yml
- README.md
- poetry.lock
- pyproject.toml
- qdrant_client/qdrant_fastembed.py
- tests/test_fast_embed.py
- Fix type in `_embed_documents` - should always return `List[float]`
- Fix `query_embed` usage
- Use fastembed dependency as `extras`, so the version compatibility is enforced by qdrant client. Also, it should be installed as `qdrant-client[fastembed]`
> fix fastembed for pydantic 1.x

- qdrant_client/conversions/common_types.py
- qdrant_client/qdrant_remote.py
IDE used to highlight types after using `get_args_subscribed`
> fix: fix type hint for get_args_subscribed and batch operation

- qdrant_client/local/local_collection.py
- qdrant_client/local/persistence.py
Local mode uses SQLite under the hood
In some cases SQLite is not threadsafe, it depends on the `THREADSAFE` variable.
https://sqlite.org/compile.html#threadsafe
By default sqlite is threadsafe on linux.
This PR suggests to allow to use local mode in a multithreading environment when THREADSAFE==1 
Previously mentioned in 
#329 #369
> new: add multithreading for local mode in Linux

- qdrant_client/async_qdrant_client.py
- qdrant_client/qdrant_client.py
- tests/test_qdrant_client.py
> new: prohibit setting more than one param from host, url, location, path

- .github/workflows/integration-tests-macos.yml
- .github/workflows/integration-tests.yml
- pyproject.toml
- tests/integration-tests.sh
```
---
* Add Discovery API (discovery and context search) - https://github.com/qdrant/qdrant-client/pull/319 by @coszio
- **Discovery search**: Uses a target and context pairs to limit the search space during the search
- **Context search**: Using only the context pairs, get the points that live in the best zone
* Add Sparse vectors support - https://github.com/qdrant/qdrant-client/pull/378 by @agourlay
- Combine the dense and sparse vectors to build hybrid search
* Add Manhattan distance support - https://github.com/qdrant/qdrant-client/pull/391 by @generall
* Add custom shard key API - https://github.com/qdrant/qdrant-client/pull/391 by @generall
- Configure how to distribute points among shards
---
* https://github.com/qdrant/qdrant-client/pull/337 - Add `wait` parameter to snapshots …
```
> bump version to v1.7.0

- qdrant_client/local/async_qdrant_local.py
- qdrant_client/local/qdrant_local.py
#365 
I haven't been able to reproduce this issue, despite trying all the code samples from the issue and some modifications from my side.
It is a workaround to replace an annoying exception with an annoying log message, more informative one (hopefully)
> fix: do not try to close none objects in local mode

- qdrant_client/local/async_qdrant_local.py
- qdrant_client/local/qdrant_local.py
Sometimes portalocker module being deleted even before deletion of QdrantLocal
In this case when `__del__` method in QdrantClient being called, we can already don't have portalocker object and calling unlock on it will cause an error `NoneType...` https://github.com/qdrant/qdrant-client/issues/365
> fix: fix portalocker being deleted before closing the client

- qdrant_client/async_qdrant_client.py
- qdrant_client/async_qdrant_remote.py
- qdrant_client/qdrant_client.py
- qdrant_client/qdrant_remote.py
- qdrant_client/uploader/grpc_uploader.py
- qdrant_client/uploader/rest_uploader.py
- qdrant_client/uploader/uploader.py
- tests/test_qdrant_client.py
> new: add shard keys to upload_collection and upload_records

- poetry.lock
- pyproject.toml
There is a [question](https://github.com/qdrant/qdrant-client/issues/390) regarding the reasons behind python version upper cap.
AFAIK there were some problems with dependencies, which no longer persist.
Some additional possible [motivation](https://iscinumpy.dev/post/bound-version-constraints/#tldr:~:text=versions%20still%20exist.-,TL%3BDR,-Capping%20dependencies%20has) for the unlock.
> new: unlock python upper cap

- qdrant_client/local/distances.py
numpy does not raise an exception in case of division by zero, but instead emits RuntimeWarning about invalid elements
> fix: fix division by zero in cosine similarity in local mode

- qdrant_client/migrate/migrate.py
Resolve vector count mismatch during client migration. The problem was due to missing `<wait=True>` in the `<upload_records>` calls. This commit adds `<wait=True>` to ensure proper synchronization and resolves the vector count mismatch.
> Fix Vector Count Mismatch during Client Migration #403

- qdrant_client/local/local_collection.py
- qdrant_client/local/qdrant_local.py
- tests/congruence_tests/test_updates.py
- tests/test_in_memory.py
> fix: fix upsert check in local mode

- qdrant_client/local/local_collection.py
- qdrant_client/local/sparse.py
- tests/congruence_tests/test_sparse_search.py
- tests/fixtures/points.py
- tests/test_local_persistence.py
> Fix sort sparse vectors

- qdrant_client/conversions/conversion.py
- tests/test_qdrant_client.py
Fixes the gRPC conversion for batch search requests containing sparse vectors.
> Fix gRPC conversion for sparse search batch

- qdrant_client/async_qdrant_client.py
- qdrant_client/qdrant_client.py
QdrantClient has the same method signatures as QdrantRemote
However, grpc_grace is present in QdrantRemote.close and is missing in QdrantClient.close
> fix: add grpc_grace param to close in QdrantClient

- qdrant_client/local/distances.py
Follows the same fix that was made in core (qdrant/qdrant#3374) for congruence
> Fix potential edge case scoring in context search

- qdrant_client/async_qdrant_fastembed.py
- qdrant_client/qdrant_fastembed.py
To be merged into the `upgrade-fastembed-version` branch. #493.
Updates `qdrant_fastembed.py` and `async_qdrant_fastembed.py` to use `list_supported_models()` from FastEmbed to set the `SUPPORTED_MODELS` value.
Resolves https://github.com/qdrant/fastembed/issues/95.
> refactor: use list_supported_models() from FastEmbed

- qdrant_client/local/async_qdrant_local.py
- qdrant_client/local/qdrant_local.py
When the close() method of the QdrantLocal class is called,
it should also close() the file 'self._flock_file'.
> Fix for close() method of QdrantLocal class

- qdrant_client/conversions/conversion.py
- tests/conversions/fixtures.py
For client Qdrant 1.8, we no longer need to support both deprecated and undeprecated fields, so this PRs removes these extra conversions.
> remove deprecated field conversions

- qdrant_client/uploader/grpc_uploader.py
- qdrant_client/uploader/rest_uploader.py
* [ X ] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [ X ] Have you followed the guidelines in our Contributing document?
* [ X ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
The current retry logic in the uploader code invokes the upsert operation `max_retries` times, regardless of whether the request succeeds or fails. Then, an exception is raised if the last of the attempts fails. The code should instead `break` upon a successful request and `return True`.
> Break out of retry loop upon successful upsert

- qdrant_client/conversions/common_types.py
- qdrant_client/local/distances.py
- qdrant_client/local/local_collection.py
- tests/congruence_tests/test_search.py
if we pass unexpected type to search, check `isinstance(query_vector, QueryVector)` fails when it gets to numpy arrays
> fix: fix QueryVector isinstance check in local mode

- qdrant_client/async_qdrant_fastembed.py
- tools/async_client_generator/fastembed_generator.py
Remove async from sparse_embedding_model_name property
Prevents:
```
ValueError: Unsupported embedding model: <coroutine object AsyncQdrantFastembedMixin.sparse_embedding_model_name at 0x7f7f0e863d00>. Supported models: {'prithvida/Splade_PP_en_v1': {'model': 'prithvida/Splade_PP_en_v1', 'vocab_size': 30522, 'description': 'Misspelled version of the model. Retained for backward compatibility. Independent Implementation of SPLADE++ Model for English', 'size_in_GB': 0.532, 'sources': {'hf': 'Qdrant/SPLADE_PP_en_v1'}}, 'prithivida/Splade_PP_en_v1': {'model': 'prithivida/Splade_PP_en_v1', 'vocab_size': 30522, 'description': 'Independent Implementation of SPLADE++ Model for English', 'size_in_GB': 0.532, 'sources': {'hf': 'Qdrant/SPLADE_PP_en_v1'}}}
```
> Remove `async` from `sparse_embedding_model_name` property

- qdrant_client/local/distances.py
While running congruence tests locally I could see the warning
`RuntimeWarning: invalid value encountered in scalar divide` for `test_sparse_recommend.py::test_simple_recommend`
Printing the `x` value shows that it is `-inf`.
> Remove warning for scalar divide with inf

- qdrant_client/local/payload_filters.py
Our congruence tests are broken since we fixed our implementation on the server side for geo bounding box crossing the antimeridian https://github.com/qdrant/qdrant/pull/4103
This PR propagates the fix to the local mode to fix our congruence tests.
> Fix local mode geo box for antimeridian crossing

- qdrant_client/async_qdrant_client.py
- qdrant_client/qdrant_client.py
> fix: QdrantClient __init__ docstring

- qdrant_client/local/local_collection.py
#624 suggests to return deepcopy of payload from scroll/search/etc api, so any changes to the payload returned by these operations won't affect the state of the payload in the db
However, it does not consider a case when the original payload which has been uploaded to db will be changed
e.g.
```
payload = {"a": {"b": 1}}
...
client.upsert(..., points=[PointStruct(..., payload=payload)])
...
payload["a"]["b"] = 2  # affects the payload in the db
```
This PR fixes this behaviour
> new: deepcopy new payload

- qdrant_client/local/local_collection.py
> new: return copy of payload

- qdrant_client/conversions/conversion.py
- tests/conversions/fixtures.py
Integer index params conversion was not added when we made integer index configurable
> fix: fix integer index conversion

- qdrant_client/http/models/models.py
This branch has not been generated from the latest dev openapi.json in qdrant repository, nor from the latest master openapi.json, but from this master branch [commit](https://github.com/qdrant/qdrant/commit/632ec541e28ffc8450909e52102c6ade5715a357).
It was done in order to have changes only related to the fix.
> fix: fix bool filters for pydantic<2.6

- qdrant_client/async_client_base.py
- qdrant_client/async_qdrant_client.py
- qdrant_client/async_qdrant_fastembed.py
- qdrant_client/async_qdrant_remote.py
- qdrant_client/client_base.py
- qdrant_client/conversions/common_types.py
- qdrant_client/local/async_qdrant_local.py
- qdrant_client/local/local_collection.py
- qdrant_client/local/qdrant_local.py
- qdrant_client/qdrant_client.py
- qdrant_client/qdrant_fastembed.py
- qdrant_client/qdrant_remote.py
Replace int and str type to PointId to improve readability
Return QueryResponse in query methods instead of scored points
This PR does not include implementation of result conversion for local mode, as #659 has not yet been merged
> new: update query signature, id type and return type

- qdrant_client/local/local_collection.py
- tests/congruence_tests/test_query.py
Currently this PR contains 2 new cases:
1. request without both `prefetched` and `query` fields
2. request with filtered prefetch
3. prefetch with score_threshold
4. prefetch with params
5. query with params
Note: the 2nd, 3d tests are failing right now
> tests: Add more tests cases (prefetch and more).

- tests/congruence_tests/test_query.py
A tiny PR which adds a test for the case fixed in qdrant/qdrant#4611. No changes required in local mode since it was working fine.
> universal-query: Test scrolling query with offset

- tests/congruence_tests/test_query.py
- tests/integration-tests.sh
I've accidentally merged a test #676 into master, requiring a fix in the core which has not yet been released, adding a version check to avoid launching on versions below 1.10.1
> fix: skip no prefetch query test if version is low

- qdrant_client/conversions/conversion.py
- tests/congruence_tests/test_query.py
- tests/conversions/fixtures.py
this pr fixes 2 bugs
1) search with sparse vectors via query with grpc
2) upsert multivec points with grpc
> fix: fix grpc conversion bugs for sparse and multi vectors

- pyproject.toml
- tools/DEVELOPMENT.md
Bumps the poetry dev version to 1.10.0-dev, from 1.4.0. In the same way that we do for the core repo
> Bump to `v1.10.0-dev`

- qdrant_client/_pydantic_compat.py
- qdrant_client/conversions/conversion.py
- qdrant_client/local/local_collection.py
- tests/congruence_tests/test_updates.py
> fix: fix conversion of datetime objects to grpc

- docs/source/quickstart.ipynb
Since `recreate_collection` is deprecated.
Thanks to https://discord.com/channels/907569970500743200/1149327864936808529/threads/1263871151990374410
> docs: Removed recreate_collection quickstart.ipynb

- qdrant_client/conversions/conversion.py
- qdrant_client/hybrid/fusion.py
- qdrant_client/local/local_collection.py
- tests/congruence_tests/test_query.py
- tests/conversions/fixtures.py
Uses interface update from #690 
Adds the local mode for Distribution-Based Score Fusion
> Distribution-based score fusion in local mode

- qdrant_client/async_qdrant_client.py
- qdrant_client/qdrant_client.py
- Added deprecation warnings for rest property
- refs: #597
> deprecate: mark rest property as deprecated in QdrantClient

- qdrant_client/qdrant_client.py
- qdrant_client/qdrant_remote.py
- Deprecated multiple async gRPC methods in favor of AsyncQdrantClient and QdrantClient.
- Added deprecation warnings for each method.
refs: #592 
> deprecate: mark async gRPC properties as deprecated in QdrantRemote

- qdrant_client/async_qdrant_remote.py
- qdrant_client/qdrant_remote.py
- tests/test_qdrant_client.py
we forgot to use conversion for parametrized payload indices in `create_payload_index`
this PR adds the necessary invocations
a bug in core was found related to the creation of parametrized geo and bool indices
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.INVALID_ARGUMENT
details = "field_type (Geo) and field_index_params do not match"
debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"field_type (Geo) and field_index_params do not match", grpc_status:3, created_time:"2024-08-20T21:42:22.125081+02:00"}"
```
There are new tests, which can reproduce this error (`tests/test_qdrant_client.py::test_create_payload_index`)
grpc code snippet to reproduce the issue:
```python
from qdrant_client import grpc
from …
```
> fix: fix conversion in create_payload_index, add tests

- qdrant_client/local/async_qdrant_local.py
- qdrant_client/local/qdrant_local.py
- tests/congruence_tests/test_query.py
Having multiple nested prefetches does not seem to work with qdrant in local mode. The last prefetch in the chain is none which then raises an exception in the _resolve_prefetch_input method:
`if prefetch.query`
raises an exception since prefetch is none)
> Fix nested prefetches in qdrant_local.py

- qdrant_client/async_qdrant_remote.py
- qdrant_client/qdrant_remote.py
- tests/test_async_qdrant_client.py
This PR only removes invalid `await` clause from initialising grpc request. The existing `await` was causing folowing exception (on version 1.11.2): 
```python
2597     if isinstance(shard_key, get_args_subscribed(models.ShardKey)):
2598         shard_key = RestToGrpc.convert_shard_key(shard_key)
-> 2599     request = await grpc.CreateShardKey(
2600         shard_key=shard_key,
2601         shards_number=shards_number,
2602         replication_factor=replication_factor,
2603         placement=placement or [],
2604     )
2605     return (
2606         await self.grpc_collections.CreateShardKey(
2607             grpc.CreateShardKeyRequest(
(...)
2611         )
2612     ).result
2613 else:
TypeError: object CreateShardKey can't be used in 'await' expression
```
I've tested the local …
> Removed invalid await from grpc async call

- qdrant_client/local/local_collection.py
Numpy 2 dropped support for the np.INF and NINF and instead it recomends np.inf and - np.inf
WIP: I'm still looking for the contribution guide, inparticular the how to run the tests locally bit, as I'm not familiar with poetry. Tests pass in the runners but I'm pretty sure the current test suite doesn't cover the changed code.
> Remove-np-ninf

- qdrant_client/http/models/models.py
#771 
For this PR I generated rest client code from https://github.com/qdrant/qdrant/commit/a2fefb48ed8b360efa121a080e7f136619708305
And manually removed not related chunks for facets, distance matrix api and some others
> fix: make resharding operations optional

- qdrant_client/async_qdrant_fastembed.py
- qdrant_client/qdrant_fastembed.py
> chore: Change embed to query_embed in fastembed mixin for sparse models

- qdrant_client/async_qdrant_client.py
- qdrant_client/async_qdrant_fastembed.py
- qdrant_client/qdrant_client.py
- qdrant_client/qdrant_fastembed.py
- tools/generate_docs_netlify.sh
spinx has started complaining on docstrings formatting and this pr addresses it
> fix: fix docstrings to make sphinx happy

- qdrant_client/async_qdrant_client.py
- qdrant_client/qdrant_client.py
Show deprecation message to methods that are suppressed by query_points (recommend, discover, search, context search)
> deprecate: Added deprecations for methods superseded by query_points

- qdrant_client/_pydantic_compat.py
- qdrant_client/embed/schema_parser.py
We're still supporting pydantic v1, it has some discrepancies in methods with pydantic v2, this pr addresses model_json_schema discrepancy
> fix: fix model json schema compat, fix fields inspected for inference

- README.md
- docs/source/index.rst
> docs: Reference api.qdrant.tech in README.md instead

- qdrant_client/qdrant_client.py
- qdrant_client/qdrant_remote.py
- tests/test_async_qdrant_client.py
- tests/test_qdrant_client.py
- tools/async_client_generator/client_generator.py
- tools/async_client_generator/remote_generator.py
- tools/async_client_generator/transformers/remote/import_from_transformer.py
* [ *] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [ *] Have you followed the guidelines in our Contributing document?
* [ *] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
1. [ *] Does your submission pass tests?
2. [ *] Have you installed `pre-commit` with `pip3 install pre-commit` and set up hooks with `pre-commit install`?
* [ *] Have you successfully ran tests with your changes locally?
> Removed async_grpc

- qdrant_client/async_qdrant_remote.py
- qdrant_client/qdrant_remote.py
- tests/test_async_qdrant_client.py
- tests/test_qdrant_client.py
Added coverage to both the async and regular client to ensure this bug doesn't come back up again.
1. [X] Does your submission pass tests? (https://github.com/rovermicrover/qdrant-client/actions/runs/12604938662/job/35132830550)
2. [X] Have you installed `pre-commit` with `pip3 install pre-commit` and set up hooks with `pre-commit install`?
> Fix for if a path is given for a remote client URL it is stored as the prefix and not discarded.

- qdrant_client/local/local_collection.py
- tests/congruence_tests/test_delete_points.py
Now deletion of non-persistent points in local mode does not throw error
> Delete non-existant points test

- qdrant_client/async_qdrant_remote.py
- qdrant_client/qdrant_remote.py
- tests/test_common.py
Replace `check_version` with `check_compatibility` in warnings and tests to fit flag name
For example it fix this place:
https://github.com/qdrant/qdrant-client/blob/64311d3a19b644647f73f2ac143902f4203a3d77/qdrant_client/qdrant_remote.py#L210
https://github.com/qdrant/qdrant-client/blob/64311d3a19b644647f73f2ac143902f4203a3d77/qdrant_client/qdrant_remote.py#L219
> fix: use the same name for `check_compatibility` flag in args, warnings and tests

- qdrant_client/async_qdrant_client.py
- qdrant_client/async_qdrant_remote.py
- qdrant_client/common/version_check.py
- qdrant_client/local/async_qdrant_local.py
- qdrant_client/local/qdrant_local.py
- qdrant_client/qdrant_client.py
- qdrant_client/qdrant_remote.py
- tests/congruence_tests/test_collections.py
it is no longer requested to specify vectors_config when creating a collection with sparse vectors only
```python
from qdrant_client import QdrantClient, models
cl = QdrantClient()
cl.create_collection(
'test', 
vectors_config={}, 
sparse_vectors_config={"sparse": models.SparseVectorParams()}
)
```
->
```python
from qdrant_client import QdrantClient, models
cl = QdrantClient()
cl.create_collection(
'test', 
sparse_vectors_config={"sparse": models.SparseVectorParams()}
)
```
> Optional vectors config

- qdrant_client/async_qdrant_fastembed.py
- qdrant_client/embed/embedder.py
- qdrant_client/embed/model_embedder.py
- qdrant_client/qdrant_fastembed.py
- tests/embed_tests/test_local_inference.py
According to the benchmarks we ran, a large inference batch size on cpu usually leads to a worse performance for both text and image objects, thus we're decreasing the default value to 8 (might be machine dependant)
> Default inference batch size

- qdrant_client/_pydantic_compat.py
- qdrant_client/embed/type_inspector.py
- tools/populate_inspection_cache.py
due to incorrect access to `model_fields_set` the following upsert was failing in pydantic v1
```python
from qdrant_client import QdrantClient, models
if __name__ == '__main__':
client = QdrantClient(":memory:")
collection_name = "test"
client.create_collection(
collection_name=collection_name,
sparse_vectors_config={
"text": models.SparseVectorParams(),
},
)
client.upsert(
collection_name=collection_name,
points=[
models.PointStruct(
id=1,
vector={
"text": models.SparseVector(
indices=[1, 3, 5, 6],
values=[0.1, 0.2, 0.3, 0.4],
)
},
)
],
)
```
> fix: model fields set and model config access

- tools/generate_grpc_client.sh
- tools/generate_rest_client.sh
Now:
Rest client should not break environment by downgrading pydentic to version 1.10
GRPC client generation should execute in a separate python environment of python3.10 and should not also break environment
> Rest & grpc client generation fix

- qdrant_client/async_qdrant_remote.py
- qdrant_client/qdrant_remote.py
- tests/test_qdrant_client.py
Bumps <https://github.com/qdrant/qdrant-client/pull/861>
Change the first user agent component of the Python client from `qdrant-client/1.2.3` to `python-client/1.2.3`.
It makes it consistent with the other clients we have. I get that this repo is called `qdrant-client`, but I'd argue `python-client` more clearly shows Python is used.
Note that cloud requested this as part of their client notification efforts.
> Change user agent to python-client

- qdrant_client/local/sparse_distances.py
Simple nearest neighbours search requires dot product between non-overlapping vectors to produce -inf (so there are no points in the results if there are no overlap between indices of sparse vectors).
However, for methods such as recommend (with strategy != average), discovery and context 0.0 distance is assumed.
> Sparse no overlap distance computation

- .github/workflows/integration-tests.yml
- qdrant_client/local/sparse_distances.py
- tests/congruence_tests/test_common.py
- tests/integration-tests.sh
We frequently have a float precision related error in tests.
Example:
```python
E       AssertionError: point1[839].id = 724, point2[839].id = 361
E       assert 724 == 361
E        +  where 724 = ScoredPoint(id=724, version=0, score=-0.007863790728151798, payload={'id': 824, 'id_str': ['01', '12', '06'], 'text_da...: False, 'mixed_type': [0.45113, 0.18627, 0.33103], 'maybe': 'octopus'}, vector=None, shard_key=None, order_value=None).id
E        +  and   361 = ScoredPoint(id=361, version=45, score=-0.007863835, payload={'id': 461, 'id_str': ['12'], 'text_data': 'f46232dc6f2143...': True, 'mixed_type': 0.40555, 'maybe': 'ant', 'maybe_null': 'spider'}, vector=None, shard_key=None, order_value=None).id
```
Python and Rust can produce slightly different results of distance computation for the …
> new: relax test comparison

- qdrant_client/conversions/conversion.py
- tests/conversions/fixtures.py
Conversion to grpc for `is_empty` field condition was broken because python returns `False` for `None` and also for `False` in `if model.is_empty`
> fix `is_empty/is_null=False` conversion to grpc

- qdrant_client/conversions/conversion.py
- tests/conversions/test_validate_conversions.py
conversion of inference objects was broken when options=None
tests did not catch it, because we do conversions from grpc to rest and then from rest to grpc, which was working fine because after the first conversion we were loosing None in favour of an empty dict
> fix: fix grpc document, image, inference object without options conversion

- qdrant_client/embed/_inspection_cache.py
- qdrant_client/http/models/models.py
Core openapi schema was not up-to-date and did not contain replacement of HardwareUsage with Usage in responses.
This PR updates models with the [fix](https://github.com/qdrant/qdrant/pull/6967)
> fix: fix openapi usage structure
